[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[variables]
NIXPACKS_SPA_OUT_DIR = "dist"

[start]
cmd = ""