[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/nixos-24.05.tar.gz"

nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[variables]
NIXPACKS_SPA_OUT_DIR = "dist"

[start]
cmd = ""